"""Generate LLM-friendly documentation indexes (llms.txt pattern, like Hermes).

Outputs, under docs/architecture/:
  llms.txt       — curated index: every doc page with a one-line description
  llms-full.txt  — all docs concatenated into one markdown file (one-shot
                   ingestion for agents)

Regenerate after doc changes:  python scripts/gen-llms-txt.py
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs" / "architecture"
OUT_INDEX = DOCS / "llms.txt"
OUT_FULL = DOCS / "llms-full.txt"

# (filename, one-line description) — keep in reading order.
MANIFEST = [
    ("README.md", "Layer reference index: navigation, numbers snapshot, system overview diagram, reading paths, main data flows, design principles"),
    ("l1-kernel.md", "Kernel: process table, sync, event bus, constitution, GateChain G1-G5, port abstractions, 889 params constants"),
    ("l2-shell.md", "Shell: 46 commands, i18n, completer, agent selector, dict-in/dict-out handler contract"),
    ("l3-card-lifecycle.md", "Card lifecycle: produce (L3A cardwrite) -> execute (plan/agents/tools) -> approve (GateChain/approval gate) -> complete -> R4 archive, with state diagram"),
    ("l3-memory.md", "Memory: 4 rings + side-channels (Mer symbolization, R5 graph, user profile) + system-prompt injection, with Mer pipeline diagram"),
    ("l3a-central.md", "L3A decision layer: sessions, l3a_ask clarification, cardwrite, profile consumption, session/ask state machines, session contract endpoints"),
    ("l3-tools.md", "Tool layer: 19 implementations by domain + tool system (spec/registry/policy/9-step pipeline)"),
    ("l3-cell-os.md", "Cell runtime: 19 SoC components (I-Cache, MMU, PMU, Watchdog, Interrupt, Rollback, Permission...) + boot/install/lifecycle/wiring"),
    ("l3-scheduler.md", "Scheduler: 5D matrix (route/pool/time/rate/scope) + ACB + safety layers (loop detectors, sequence monitor, think registry)"),
    ("l3-convention.md", "Cross-cell deliberation: orchestrator -> answer sessions -> aggregator -> supplements -> report, with flow diagram"),
    ("l4-bridge.md", "Bridge: 263 routes, API gateway, LLM engine, SSE/WS/RPC channels, auth/fs contracts, sandbox, with message/auth sequences"),
    ("l5-user.md", "User layer: CLI entry, CLI/TUI/desktop contract tiers"),
    ("cross-cutting.md", "Cross-cutting: governance, event flow, system-prompt injection switches, session anti-blowup, testing/QA, skills lifecycle, collaboration discipline"),
]


def main() -> None:
    # ── llms.txt (index) ──
    lines = [
        "# Praxis Agent OS — Architecture Docs",
        "",
        "Five-layer Agent Operating System. Entry point:",
        "docs/architecture/README.md (navigation + generated numbers + design principles).",
        "",
        "## Index",
        "",
    ]
    for fname, desc in MANIFEST:
        lines.append(f"- [{fname}]({fname}): {desc}")
    lines.append("")
    lines.append("> Generated by scripts/gen-llms-txt.py — regenerate after doc changes.")
    OUT_INDEX.write_text("\n".join(lines), encoding="utf-8")

    # ── llms-full.txt (concatenation for one-shot ingestion) ──
    chunks = [f"# Praxis Agent OS — Full Architecture Documentation\n",
              "> Concatenated for one-shot LLM ingestion. Generated by",
              "> scripts/gen-llms-txt.py; regenerate after doc changes.\n"]
    for fname, _desc in MANIFEST:
        src = DOCS / fname
        if not src.exists():
            continue
        text = src.read_text(encoding="utf-8")
        # strip yaml-ish fences noise? keep as-is; just delimit pages
        chunks.append(f"\n\n---\n\n# Source: {fname}\n\n")
        chunks.append(text)
    OUT_FULL.write_text("".join(chunks), encoding="utf-8")

    print(f"wrote {OUT_INDEX.relative_to(ROOT)} ({OUT_INDEX.stat().st_size} bytes)")
    print(f"wrote {OUT_FULL.relative_to(ROOT)} ({OUT_FULL.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
